### PR TITLE
WIP: Fix README

### PR DESCRIPTION
**Pull request by noe-code**
First attempt

### CODE REVIEW

**Comment by davidgchaves** [comment]
:-)
Great.

Let's try with another commit.

**Comment by davidgchaves** [comment]
@noe-code 
Are you getting the notification?

**Comment by noe-code** [comment]
Only the one with the explicit mention

**Comment by davidgchaves** [comment]
I got them, even with no direct mentions.

**Comment by noe-code** [comment]
README fixed.

**Comment by noe-code** [comment]
I think it's ready

**Comment by davidgchaves** [comment]
Nice :)

Let's try squashing the 3 commits into 1.

**Comment by noe-code** [comment]
Done :+1:

**Comment by davidgchaves** [comment]
Yay!
👍

**Pull request merged**
